package com.example.sqlite.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yikangcheng.admin.yikang.greendao.SoSuoDb;

import com.example.sqlite.dao.SoSuoDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig soSuoDbDaoConfig;

    private final SoSuoDbDao soSuoDbDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        soSuoDbDaoConfig = daoConfigMap.get(SoSuoDbDao.class).clone();
        soSuoDbDaoConfig.initIdentityScope(type);

        soSuoDbDao = new SoSuoDbDao(soSuoDbDaoConfig, this);

        registerDao(SoSuoDb.class, soSuoDbDao);
    }
    
    public void clear() {
        soSuoDbDaoConfig.clearIdentityScope();
    }

    public SoSuoDbDao getSoSuoDbDao() {
        return soSuoDbDao;
    }

}
